### ISSUE TITLE
Advanced Types Add-on API

### ISSUE THREAD

**Issue by rm-rf-etc** [rm-rf-etc/simple-shared-state#4]
Advanced Types in substrate should be easy to add. Inside of [specialTypes.js](https://github.com/rm-rf-etc/react-substrate/blob/20c4edec33d01fbaad455aa66544fda9af1753dd/specialTypes.js), the `specialTypes` object should be extended with any modular external advanced type. Inside of `events.on('data_loaded'` callback, any rehydration process can run on the loaded event.

```javascript
const specialTypes = {
	stringified: {
		default: [],
		path: null,
		retrieve(subject) {
			const result = JSON.parse(subject);
			result.push = arrayMethodOverrides.push.bind(result);
			result.concat = arrayMethodOverrides.concat.bind(result);
			return result;
		},
		store(subject) {
			return JSON.stringify(subject);
		},
	},
	dimensional: {
		default: 0, // required
		path: '__schematype_dimensional__', // required
		rehydrate(node) { // specific to this type
			console.log('rehydrate?', omit(node, '_'));
		},
		add(...args) { // specific to this type
			const d = args.length || 1;
		},
		store() { // required
			return 1;
		},
		retrieve() { // required
			return 1;
		},
	},
};
```
The `path` property indicates that our advanced type will store additional, or helper data, somewhere. Path is where we put that data, and `rehydrate` will read from here on startup.

**Comment by Dletta** [comment]
What other special types would you need?

**Comment by rm-rf-etc** [comment]
So... I've changed some of the terms I'm using. Instead of advanced types, I'm calling these just "data structures" or "structures". In the latest code, Weir invokes a structure called `generic` if the developer provides a plain object when declaring the bucket:
```javascript
export default bucket(" ...label... ", {
    state: { ... },
    methods: ({ ... }) => ({ ... }),
})
```
To use any external data structure, such as the dimensional data structure (will eventually be moved out to a standalone module), the developer simply wraps this object in the method call:
```javascript
export default bucket(" ...label... ", dataStructure({
    dataStructureSpecific1: ... ,
    dataStructureSpecific2: ... ,
    dataStructureSpecific3: ... ,
    ...
    methods: ({ ... }) => ({ ... }),
}));
```

I haven't finished a fully useable dimensional data structure but it's getting there. I've been confused as to how the methods should work, but I think I'm getting more clear on it now that I'm able to build some simple apps with `generic` and see how things work out as layers of functionality add up.

I think it would make sense to have a data structure for time-series data, which I think would actually be very similar to the dimensional data structure. I know we can use `.set` for time series data, but how do we query it? In a chat application, how do we get only the last N messages and paginate after that? Is this already in gun or do we need tags to make this work?

Slight tangent: these structures could be pre-packaged with working UI components so app developers could literally drop them in and expect everything to *quite literally* "just work".

I think a full-text search would require it's own specialized data structure. It would have some similarities to the dimensional data structure but probably some really big departures too.

Paginated data also... perhaps we could have a structure which can paginate any arbitrary list of things and this could be used in tandem with any of the other data structures thanks to a new feature which I will be writing but haven't started on yet, which I think will be called "pumps". The idea is you take two or more buckets, and you setup listeners between them, so when something happens in bucket A, it drives your changes in bucket B, or any number of other buckets. Basically it's any data-flow logic that happens independently of components.

**Comment by rm-rf-etc** [comment]
Generic:
https://github.com/rm-rf-etc/weir/blob/wip/src/structures/generic.js
Dimensional:
https://github.com/rm-rf-etc/weir/blob/wip/src/structures/dimensional.js
